### ISSUE TITLE
Not using native titlebar on linux

### ISSUE THREAD

**Issue by Melechtna** [commetchat/commet#392]
As the title says, this messenger is nearly perfect for my use case, however, it has about 3 hitches that make it just shy of what I need.

First, pinned messages, element has supported this in labs for about a year, and within about the past 2 months, has integrated it as a native feature, and it's kind of always been a must have in my daily life.

Second, voice/video chat, more specifically group. To explain, in the room I'd created in element, I have a group voice/video chat, which this feature seems to be in eternal lab status, but, I can't even see how to do this for 1 on 1 calls.

Lastly, and this one is likely more Linux centric, maybe, but, an option to do away with the UI's titlebar, and to instead use the systems native title bar. The one it defaults too is the size of a twinky and is just cumbersome.

That's basically it, if these 3 things were implimented, I'd swap absolutely everyone I dragged over to element to get away from Discord to this.

**Comment by Airyzz** [comment]
Totally agree with all of these! i wasn't aware of the issue with title bars, so I'll look in to getting that resolved soon! 

pinned messaged should be pretty straight forward too.

calls are a work in progress, currently only 1:1 though. i fully intend to get group calls going as well, but currently I'm focused on getting 1:1 working well first.

thanks for the feedback!

**Comment by Melechtna** [comment]
![image](https://github.com/user-attachments/assets/925d623b-fddf-403e-a01a-51e8684ef68e)
Yeah, it's a bit much

**Comment by Melechtna** [comment]
Also, I guess while I have you here, not really a need, but more a "would be nice" is if the room list used the icons set for them, but I'm really not fussed about that one.

**Comment by Airyzz** [comment]
yea for sure, should be pretty quick to do

**Comment by Melechtna** [comment]
Okay, I have banged my head against the wall trying to get this to work, and the issue seems to be multi-faceted.

Problem 1. GTK3 has made it absolutely rediculous to disable client side decorations, this is doable by using the window-manager to simply discard the title bar.

Problem 2. This will require 2 imports in either the window manager or main, of which this is my hacky attempt at it, or at least the last one, I don't have the code I was using to do away with the titlebar anymore.

```
import 'dart:ffi';
import 'dart:io';
import 'package:commet/config/build_config.dart';
import 'package:commet/main.dart';
import 'package:window_manager/window_manager.dart';

class WindowManagement {
  static Future<void> init() async {
    if (!BuildConfig.DESKTOP) return;


    if (isQtBasedDesktop()) {
      Platform.environment['GTK_CSD'] = '0';
      loadGtk3NoCsd();
    }

    await windowManager.ensureInitialized();
    _WindowListener listener = _WindowListener();

    windowManager.setPreventClose(preferences.minimizeOnClose);
    windowManager.addListener(listener);
  }

  static String getDesktopEnvironment() {
    return Platform.environment['XDG_CURRENT_DESKTOP']?.toLowerCase() ?? 'unknown';
  }

  static bool isQtBasedDesktop() {
    final desktop = getDesktopEnvironment();
    return desktop.contains('kde') || desktop.contains('lxqt');
  }

  static void loadGtk3NoCsd() {
    try {
      final libraryPath = '${Directory.current.path}/lib/libgtk3-nocsd.so.0';
      final nativeLib = DynamicLibrary.open(libraryPath);
      print('Successfully loaded gtk3-nocsd library: $libraryPath');
    } catch (e) {
      print('Failed to load gtk3-nocsd library: $e');
    }
  }
}

class _WindowListener extends WindowListener {
  @override
  void onWindowClose() {
    super.onWindowClose();

    if (preferences.minimizeOnClose) {
      windowManager.minimize();
    }
  }
}
```

Problem 3. You'll have to import something like this
https://github.com/PCMan/gtk3-nocsd
Include the library in the bundle, and load the library when a Qt environment is detected.

I am sure there's a better way to handle this, but, hopefully this gives you an idea of how to handle the situation, unfortunately, this is purely a GTK issue, because they decided effort wasn't part of their plan, and threw out any attempts to co-exist with Qt.

**Comment by Airyzz** [comment]
Thanks so much for taking the time to look in to this! Interestingly i haven't been able to reproduce it on KDE Plasma.

![image](https://github.com/user-attachments/assets/7f2fb22b-e534-47f3-a532-0729154dbfed)

However, I did find an alternative solution proposed here https://github.com/flutter/flutter/issues/111453 which seems a bit simpler

I created branch https://github.com/commetchat/commet/pull/393 implementing this change, but since I can't reproduce the issue, I dont know that it worked. If you wouldn't mind, could you test to see if this has solved the issue for you?

**Comment by Melechtna** [comment]
> Thanks so much for taking the time to look in to this! Interestingly i haven't been able to reproduce it on KDE Plasma.
> 
> ![image](https://private-user-images.githubusercontent.com/36567925/400701590-7f2fb22b-e534-47f3-a532-0729154dbfed.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzYyNTczOTIsIm5iZiI6MTczNjI1NzA5MiwicGF0aCI6Ii8zNjU2NzkyNS80MDA3MDE1OTAtN2YyZmIyMmItZTUzNC00N2YzLWE1MzItMDcyOTE1NGRiZmVkLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNTAxMDclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjUwMTA3VDEzMzgxMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWU0ZTJiZjVmZjVhNDIxYmJhNzgwN2JlNTY0ZGY1MmNjMTBmNmIyNzEzYmE1YWM2ODFjNDRjYWNlMjllMmE5YzgmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.DNDfV_ciuZsciVQRFnV20z4Mm3Owvj9pIshklWhjSDA)
> 
> However, I did find an alternative solution proposed here [flutter/flutter#111453](https://github.com/flutter/flutter/issues/111453) which seems a bit simpler
> 
> I created branch #393 implementing this change, but since I can't reproduce the issue, I dont know that it worked. If you wouldn't mind, could you test to see if this has solved the issue for you?

Use wayland

**Comment by Airyzz** [comment]
Thanks for testing, I merged that branch and I'm going to close this issue as a result.

I split out the request for pinned messages to its own issue at #394

**Comment by snoweuph** [comment]
Looks like SSD is still a problem with the flatpak on the Cosmic Desktop.

<img width="1934" height="1079" alt="Image" src="https://github.com/user-attachments/assets/f73fa28d-c405-46fd-a69f-e7acd8a584a4" />
